### ISSUE TITLE
Strip out non-utf8 characters

### ISSUE THREAD

**Issue by Arp-G** [tallakt/codepagex#27]
I want to remove all non-utf8 characters from a string.
The closest encoding to utf-8 I found was ` :iso_8859_1`

When using the `to_string/4` I cannot find any option to pass utf8 as the first argument

I want something like this...
```
Codepagex.to_string("string", :utf8, Codepagex.use_utf_replacement())
{:error, "Unknown encoding :utf8", 0}
```

Could you please help me with this? Also is there any way I can remove all non-utf8mb4 characters?

Many thanks for this useful library.

**Comment by tallakt** [comment]
I think `Codepagex` cant really do this, because handling invalid utf8 is only related to conversion from utf-8 strings to another layout.

You could do this to strip non utf8 codepoints from a string

```elixir
is_utf8? = fn
  <<_::utf8>> -> true
  _ -> false
end
Enum.filter(String.codepoints("A" <> <<128>> <> "BC"), is_utf8?)
```
