### ISSUE TITLE
No automatic download of Unicode mappings

### ISSUE THREAD

**Issue by ronnyhartenstein** [tallakt/codepagex#3]
I installed it the normal way. `mix.exs` -> `{:codepagex, "~> 0.1.1"}`. Then `mix deps.get` and I should be done. But `Codepagex.encoding_list` returns `[]`. Hm.
Inside the projects `mix.exs` there is a alias `"codepagex.download"`. I could run it with `cd ./deps/codepagex; mix codepagex.download`.
After doing `mix deps.recompile` in my project dir it works.

Normally it should do it on `deps.get`, shouldn't it?

**Comment by tallakt** [comment]
Hmm. I will look into this. The plan was to have the codepages checked in to git. The download task was just for updating the package. Its a clear bug :) thanks

**Comment by tallakt** [comment]
I see now that the 'unicode' folder is not in the mix.exs files list. I will get this sorted out shortly.

**Comment by ronnyhartenstein** [comment]
Oh great, yes, the download took around 5 min for me. And the mappings won't change often I guess ;)
So adding it to the repo is a great idea. I'm actually not firm with mix packages in detail, so no PR yet (instantly). But I'll have a look on this topic.
