### ISSUE TITLE
Adding encodings not load 

### ISSUE THREAD

**Issue by sergey-chechaev** [tallakt/codepagex#4]
I have elixir project with _config.exs_
` use Mix.Config
  config :codepagex, :encodings, [
    :ascii,
    ~r[iso8859]i,
    "ETSI/GSM0338",
    "MISC/CP424",
    :"MISC/CP856",
    "VENDORS/MICSFT/WINDOWS/CP1251"
  ]
`
After start _iex -S mix_ i run `Codepagex.encoding_list` return `["ISO8859/8859-1", "ISO8859/8859-10", "ISO8859/8859-11", "ISO8859/8859-13",
 "ISO8859/8859-14", "ISO8859/8859-15", "ISO8859/8859-16", "ISO8859/8859-2",
 "ISO8859/8859-3", "ISO8859/8859-4", "ISO8859/8859-5", "ISO8859/8859-6",
 "ISO8859/8859-7", "ISO8859/8859-8", "ISO8859/8859-9",
 "VENDORS/MISC/US-ASCII-QUOTES"]`
without adding encodings.

`Codepagex.to_string(<<205, 232, 230, 237, 232, 233, 32, 205, 238, 226, 227, 238, 240, 238, 228>>, "VENDORS/MICSFT/WINDOWS/CP1251")` return `{:error, "Unknown encoding \"VENDORS/MICSFT/WINDOWS/CP1251\""}`

How i can convert binary to string encoding windows-1251?

**Comment by tallakt** [comment]
It is working for me. Could you try to remove the `_build` folder and recompile? Could be that the .beam files are stale....

**Comment by sergey-chechaev** [comment]
@tallakt, yes it is work, the issue is close.
