### ISSUE TITLE
Add Performance Benchmarks to the TODO

### ISSUE THREAD

**Issue by heri16** [tallakt/codepagex#6]
A graph like the one on this page will attract more interest to this project.

https://www.npmjs.com/package/jconv

**Comment by heri16** [comment]
By the way, this project is great! NIFs are inherently bad in production systems, and this might be a replacement. Also the problem set is a great way of demonstrating the use of elixir meta programming features.

**Comment by tallakt** [comment]
This is probably a good idea. I'll see if I can get around to creating a chart like the one you reference. One problem of course is that I expect iconv has better performance, but this is probably offset, as you also mention, by the fact that you are not dependent on a specific installed library for iconv.

**Comment by heri16** [comment]
NIFs are likely to be slower in the real word where there are multiple
users (above 100 concurrent users/processes). The Cowboy project has proven
this point many times over.

**Comment by tallakt** [comment]
Even more the reason to get the actual numbers. If performance is similar, that would give codepagex a significant edge over iconv solutions. Very curious at this point

**Comment by tallakt** [comment]
I have started working on this, and codepagex is faster for short (<32 codepoints) strings and better at parallellism. But iconv seems generally faster with the speed of codepagex/iconv in the range 0.5 .. 24 on my computer (4 CPU)

**Comment by heri16** [comment]
If you could post source code for the benchmarks, I could run it over on my
end. Was any benchmarking tool or framework used? Afterwards we
could optimize low hanging fruit performance bottlenecks with flamegraph
analysis?

**Comment by tallakt** [comment]
https://github.com/tallakt/codepagex_iconv_chart

Still a work in progress
