### ISSUE TITLE
Support more charset aliases like iconv

### ISSUE THREAD

**Issue by heri16** [tallakt/codepagex#7]
Support all aliases from http://www.iana.org/assignments/character-sets/character-sets.xhtml

If not possible, support at least the preferred MIME set in the first column.
## MIME Charset Registry

MIME charset tags are registered with the IANA (http://www.iana.org/numbers.htm). The charset registry is a flat-file text database of records. Each record contains a charset name, reference citations, a unique MIB number, a source description, and a list of aliases. A name or alias may be flagged "preferred MIME name."

**Comment by tallakt** [comment]
I agree. I'll se if I can add some more aliases.
